In [1]:
import numpy as np
import matplotlib.pyplot as plt

Matplotlib is building the font cache; this may take a moment.


In [6]:
# Data Structure: [restraunt_id, 2021, 2022, 2023, 2024]
sales_data = np.array([
    [1, 150000, 180000, 220000, 250000], #restraunt 1
    [2, 120000, 140000, 160000, 190000], #restraunt 2
    [3, 200000, 230000, 260000, 300000], #restraunt 3
    [4, 180000, 210000, 240000, 270000], #restraunt 4
    [5, 160000, 185000, 205000, 230000]  #restraunt 5
])

print("Shape of data is: ", sales_data.shape)
print("Size of data is: ", sales_data.size)
print("Data of firse three restraunt: ", sales_data[0:3])

Shape of data is:  (5, 5)
Size of data is:  25
Data of firse three restraunt:  [[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 190000]
 [     3 200000 230000 260000 300000]]


In [51]:
# Total sales per year
total_sales = np.sum(sales_data[0:5,1:5], axis=0)
print("Yearly total: ",total_sales)
total = np.sum(total_sales)
print("Total sales: ", total)


# Minimum sales per restraunt
min_sales = np.min(sales_data[0:5,1:5], axis=1)
print("Minimum sales per restraunt: ", min_sales)


# Maximum sales per year
max_sales = np.max(sales_data[0:5, 1:], axis=0)
print("Maximum sales per year: ", max_sales)

# Average sales per restraunt
ave_sales = np.average(sales_data[:, 1:], axis=1)
print("Average sales per restraunt", ave_sales)

Yearly total:  [ 810000  945000 1085000 1240000]
Total sales:  4080000
Minimum sales per restraunt:  [150000 120000 200000 180000 160000]
Maximum sales per year:  [200000 230000 260000 300000]
Average sales per restraunt [200000. 152500. 247500. 225000. 195000.]


In [52]:
## Cumelative sales of restraunt
cum_sales = np.cumsum(sales_data[:, 1:], axis=1)
print("Cumelative sales of restraunt: ", cum_sales)

Cumelative sales of restraunt:  [[150000 330000 550000 800000]
 [120000 260000 420000 610000]
 [200000 430000 690000 990000]
 [180000 390000 630000 900000]
 [160000 345000 550000 780000]]
