<!-- LEARN ABOUT NUMPY -->


In [1]:
import numpy as np


### Crating array from list


In [9]:
arr_1d = np.array([1,2,3])
print("the 1d array is: ",arr_1d)

arr_2d = np.array([[1,2,3], [4,5,6]])
print("the 2d array is: ", arr_2d)
print(type(arr_1d))



the 1d array is:  [1 2 3]
the 2d array is:  [[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [22]:
zeroArr = np.zeros((3,4))
print("Zeros Array: \n", zeroArr)f

onesArr = np.ones((4,3))
print("\nOnes Array: \n", onesArr)

fullArr = np.full((3,4), 10)
print("\nFull value 10 Array: \n", fullArr)

randomArr = np.random.random((3,4))
print("\nRandom values Array: \n", randomArr)

sequence = np.arange(0,11,2)
print("\nSequence values Array: \n", sequence)



Zeros Array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Ones Array: 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Full value 10 Array: 
 [[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]

Random values Array: 
 [[0.30129817 0.59768109 0.73820586 0.93326254]
 [0.47965677 0.74540284 0.47693771 0.96682533]
 [0.4762292  0.63428475 0.06540952 0.07256737]]

Sequence values Array: 
 [ 0  2  4  6  8 10]


VECTOR, MATRIX, TENSOR