<!-- LEARN ABOUT NUMPY -->


In [1]:
import numpy as np


### Creating array from list

In [9]:
arr_1d = np.array([1,2,3])
print("the 1d array is: ",arr_1d)

arr_2d = np.array([[1,2,3], [4,5,6]])
print("the 2d array is: ", arr_2d)
print(type(arr_1d))



the 1d array is:  [1 2 3]
the 2d array is:  [[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [44]:
zeroArr = np.zeros((3,4))
print("Zeros Array: \n", zeroArr)

onesArr = np.ones((4,3))
print("\nOnes Array: \n", onesArr)

fullArr = np.full((3,4), 10)
print("\nFull value 10 Array: \n", fullArr)

randomArr = np.random.random((3,4))
print("\nRandom values Array: \n", randomArr)

sequence = np.arange(0,11,2)
print("\nSequence values Array: \n", sequence)



Zeros Array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Ones Array: 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Full value 10 Array: 
 [[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]

Random values Array: 
 [[0.46894984 0.4576512  0.38863727 0.25370846]
 [0.85003389 0.04391763 0.60609148 0.93885335]
 [0.21664906 0.53624191 0.15337319 0.83314265]]

Sequence values Array: 
 [ 0  2  4  6  8 10]


### VECTOR, MATRIX, TENSOR

In [28]:
vector = np.array([1,2,3])
print("Vertor: \n", vector, vector.shape)

matrix = np.array([[1,2,3], 
                   [4,5,6]])
print("Matrix: \n", matrix, matrix.shape)

tensor = np.array([[[1,2], [3,4]],
                   [[5,6],[7,8]]])
print("Tensor: \n", tensor, tensor.shape)


Vertor: 
 [1 2 3] (3,)
Matrix: 
 [[1 2 3]
 [4 5 6]] (2, 3)
Tensor: 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]] (2, 2, 2)
lennn 2


### ARRAY PROPERTIES

In [29]:
arr = np.array([[1,2,3],
                [4,5,6]])

print("Shape: ", arr.shape)
print("Dimension: ", arr.ndim)
print("Size: ", arr.size)
print("DataType: : ", arr.dtype)

Shape:  (2, 3)
Dimension:  2
Size:  6
DataType: :  int64


### Array Reshaping

In [43]:
arr = np.arange(12)
print("Original Array: \n", arr)

reshaped = arr.reshape((3,4))
print("Reshaped Array: \n", reshaped)

flattened = reshaped.flatten()
print("Flattened Array: \n", flattened)

# returns view instead of copy
raveled = reshaped.ravel()
print("Raveled Array: \n", raveled)

transpose = reshaped.T
print("Transpose Array: \n", transpose)

Original Array: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped Array: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened Array: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled Array: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transpose Array: 
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
